
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - android-27
  - build-tools-28.0.3
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - ./gradlew build
